name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  simple_lambda_test:
    name: Simple Lambda Test
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install boto3 For Simple Test
        run: pip3 install boto3

      - name: Run Unit Test
        run: python lambda\test_simple_visit_count_lambda_function.py
